---
- name: install additional packages
  vars:
          install_state: installed
  yum:
    name:
      - telnet
      - mlocate
      - bind-utils
      - tcpdump
      - htop
      - atop
      - iotop
      - lsof
    state: "{{ install_state }}"

